# Generated by Django 4.1.6 on 2023-02-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=500)),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
